services:
  backend:
    image: backend:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network
    env_file:
      - backend/.env.backend

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    image: frontend:1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
    networks:
      - app-network
    env_file:
      - frontend/.env.frontend

networks:
  app-network:
    driver: bridge